### ISSUE TITLE
Extract/Pack in big_util

### ISSUE THREAD

**Issue by Teteros** [feliwir/libbig#3]
https://github.com/feliwir/libbig/blob/master/tools/big_util/main.cpp#L25

Not implemented yet?
Would be a very useful tool to our ZH modding env since FinalBIG isn't suited for CI/automated builds being graphical.

**Comment by feliwir** [comment]
Didn't think someone would use this :) I see what i can do

**Comment by feliwir** [comment]
@Teteros for now i can link you "bigedit" a library that i wrote earlier: https://mega.nz/#!bwBXgSbA!NjCzyqSHOz3HeToU30_CXwCxjkpHpsnFHaaMvZgAJ2o . I am currently a bit busy, but i will try to implement the writing functionality from that library asap

**Comment by Teteros** [comment]
Thanks a lot!

Are the `test.exe` and `testCS.exe` in bin used for anything? They both seem to print contents of some .big (I'm assuming `ini.big` which was included in the package) 
Then just create `test.big` and `test2.big` in their working dir.
Maybe wine is messing with it.

What's the usage?

From the name I figured testCS is for test compression but passing args yields same results.

**Comment by feliwir** [comment]
Hey, it's been years and i have no computer except my phobe atm( holiday ;) ). Here is a link to the source, you can probably figure args out from there: https://mega.co.nz/#!ThhgCKQK!EAmAersUFY6dO0Qp4QXcz1OJC_E7QxCh0eBlwPa1EUA

It was really only a library where functions must be called. I didn't write a tool fron that library

**Comment by Teteros** [comment]
[easage](https://github.com/Phrohdoh/easage) implemented this functionality with the `pack` command
